name: solus-iso-downloader
adopt-info: solus-iso-downloader
summary: An ISO downloader for Solus Linux
description: |
    An ISO downloader for Solus Linux. Download your favorite distribution of Linux without opening a browser. Perfect for VM hosts.

license: MIT

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  solus-iso-downloader:
    command: sh $SNAP/bin/solus_iso_downloader.sh
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      
parts:
  solus-iso-downloader:
    source: https://github.com/kz6fittycent/Solus_ISO_Downloader
    source-type: git
    plugin: nil
    
    override-pull: |
      VERSION=$(curl -s https://github.com/kz6fittycent/Solus_ISO_Downloader/blob/master/solus_iso_downloader.sh | head -n 150 | grep 'version' | awk '{ print $10 }')
      echo "Setting snap version to '$VERSION'"
      snapcraftctl set-version "$VERSION"
      echo "$VERSION" > version
    
    build-packages:
      - wget
      
    stage-packages:
      - wget
      
  publish:
    plugin: dump
    source: .
    organize:
      ./solus_iso_downloader.sh: /bin/solus_iso_downloader.sh
