name: solus-iso-downloader
version: 'latest'
summary: An ISO downloader for Solus Linux
description: |
    An ISO downloader for Solus Linux. Download your favorite distribution of Linux without opening a browser. Perfect for VM hosts.

license: MIT

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  solus-iso-downloader:
    command: $SNAP/bin/solus_iso_downloader
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      
parts:
  solus-iso-downloader:
    source: https://github.com/kz6fittycent/Solus_ISO_Downloader
    source-type: git
    plugin: nil
    
    build-packages:
      - wget
      
    stage-packages:
      - wget
      
  publish:
    plugin: dump
    source: .
    organize:
      ./solus_iso_downloader: /bin/solus_iso_downloader
