name: solus-iso-downloader
version: 'latest'
summary: A python-based ISO downloader for Solus Linux
description: |
    A python-based ISO downloader for Solus Linux. Download your favorite distribution of Linux without opening a browser. Perfect for VM hosts.

license: MIT

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  solus-iso-downloader:
    command: python3 $SNAP/bin/solus_iso_downloader.py
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      
parts:
  solus-iso-downloader:
    source: https://github.com/kz6fittycent/Solus_ISO_Downloader
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - python3
      - python3-pip
      - python3-tqdm
      
    stage-packages:
      - python3
      - python3-pip
      - python3-tqdm

  publish:
    plugin: copy
    files:
      ./solus_iso_downloader.py: bin/solus_iso_downloader.py
